validate token by fetching from api

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -29,7 +29,29 @@ jobs:
             fi
             DIR=`dirname $file`
           done
-          echo $DIR
+          urls=( "https://api.elrond.com/" "https://testnet-api.elrond.com/" "https://devnet-api.elrond.com/")
+          for url in ${urls[@]}; do
+            API_TOKEN_URL="$url" 
+            API_TOKEN_URL+="tokens/"
+            API_TOKEN_URL+="$DIR"
+            API_COLLECTION_URL="$url"
+            API_COLLECTION_URL+="collections/"
+            API_COLLECTION_URL+="$DIR"
+
+            HTTP_STATUS=$(curl -s -w "%{http_code}" -o /dev/null "$API_TOKEN_URL")
+            if [[ ${HTTP_STATUS} == 200 ]]; then
+              exit 0
+            fi
+            echo "Failed fetching from $API_TOKEN_URL"
+            
+            HTTP_STATUS=$(curl -s -w "%{http_code}" -o /dev/null "$API_COLLECTION_URL")
+            if [[ ${HTTP_STATUS} == 200 ]]; then
+              exit 0
+            fi
+            echo "Failed fetching from $API_COLLECTION_URL"
+          done
+
+          exit 1
         shell: bash
       - name: Validate JSON
         uses: docker://orrosenblatt/validate-json-action:latest
